version: '3.4'

services:
  consul:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8500:8500
      
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
