server:
  port: 8081

spring:
  application:
    name: quotes-service
  profiles:
    active: no-cloud
    #active: cloud

  datasource:
    url: jdbc:h2:mem:testdb

  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

quotes:
  prefix: "Кто-то сказал: "
